version: '3.8'

services:
  istation-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: istation-api
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - MAX_CONCURRENT_REQUESTS=50
      - HTTP_POOL_SIZE=100
      - REQUEST_TIMEOUT=30
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - istation-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

networks:
  istation-network:
    driver: bridge

volumes:
  logs:
  temp:
